language: java

jdk:
  - openjdk8

before_install:
  - chmod +x gradlew
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

script:
  - ./gradlew compileJava
  - ./gradlew compileTestJava
  - ./gradlew test
