INSERT INTO trips (id, name, destination, description, price, start_date, end_date, category) VALUES
    (1, 'Mendoza, más cerca de las nubes', 'Mendoza', 'Mendoza te espera para disfrutar de unos días de desconexión, en contacto con la naturaleza. Vas a descubrir el escenario perfecto para vivir una pausa bajo el encanto de sus paisajes mágicos.\n¡Escapate de la rutina y contagiate de la energía de este lugar!', 30000, '2022-01-03', '2022-01-09', 'CATEGORY1'),
    (2, 'Bosque de Arrayanes y Bariloche, postales para soñar', 'San Carlos de Bariloche', 'Sentí la magia de cada rincón de Bariloche. Navegá y descubrí la belleza del único bosque de arrayanes del mundo. Relajate en el hotel frente al lago y encontrá el plus de desconexión que necesitás para tu escapada.\nBariloche es un destino que atrapa. Sus montañas, lagos y arroyos se camuflan con el verde de la vegetación para crear postales maravillosas. Sus sabores maridan con una atmósfera de paz especial para desconectarse de la rutina y vivir de cerca la perfección de la naturaleza.\n¡Dejate tentar por el encanto de un lugar soñado y empezá a palpitar una escapada para desconectarte de verdad!', 30000, '2022-01-10', '2022-01-16', 'CATEGORY2'),
    (3, 'Salta: una aventura única', 'Salta', 'Sumergite en los paisajes de Salta y dejá que la adrenalina sea parte de tu viaje. Paisajes, naturaleza y aire puro, resultan una combinación genial hacia la aventura, que sin dudas vas a disfrutar.\nEscapate, ¡es todo lo que necesitás para olvidarte de la rutina!', 25000, '2022-01-17', '2022-01-23', 'CATEGORY3'),
    (4, 'Escapate a Ushuaia, te esperan nuevos desafíos', 'Ushuaia', 'Salí al encuentro de la naturaleza y animate a vivir nuevos desafíos en Ushuaia. Descubrí nuevos paisajes, disfrutá del aire puro y sentí la adrenalina, en una experiencia única.\nEscapate y disfrutá de una dosis de adrenalina, lejos de la rutina.', 25000, '2022-01-24', '2022-01-30', 'CATEGORY1'),
    (5, 'Carlos Paz, La Cumbrecita y General Belgrano: sierras cordobesas', 'Cordoba', 'Escapate a Carlos Paz, disfrutá de un hotel en la Villa y aprovechá de una excursión hacia dos destinos en las Sierras: La Cumbrecita y Villa General Belgrano, donde vas a encontrar un verdadero pasaje a la desconexión. En La Cumbrecita, vas a disfrutar de un pueblo peatonal, con construcciones alpinas que usan energías renovables en medio de bosques, senderos, ríos y cascadas. En Villa General Belgrano, podrás saborear las mejores cervezas artesanales. ¡Córdoba tiene todo para tu próxima escapada!', 15000, '2022-01-31', '2022-02-06', 'CATEGORY2'),
    (6, 'Carlos Paz, Mina Clavero y Cura Brochero: una escapada a las sierras', 'Cordoba', 'Disfrutá de una escapada a Carlos Paz y dejá que el aire de las sierras renueve tu energía en un tour de día completo hacia Cura Brochero, Los Túneles y Mina Clavero. Regalate la oportunidad de descansar, disfrutá de tu hotel con desayuno y piscina climatizada y descubrí paisajes donde las sierras y ríos cristalinos son protagonistas. Si buscás una escapada para desconectar, tu destino está en Carlos Paz.', 15000, '2022-02-07', '2022-02-13', 'CATEGORY3'),
    (7, 'Cariló, una pausa en medio del bosque', 'Carilo', 'Escapate a Cariló y disfruta de unos días de desconexión rodeado de bosques de pinos, acacias y aromos. Regalate la oportunidad de regresar a lo natural, caminar frente al mar y disfrutar lejos de la rutina. Te espera un hotel con desayuno y todo el confort para descansar.\nLa tranquilidad y calidez de Cariló convierten a este destino en un lugar ideal para recargar energías. Los bosques, médanos y playas son protagonistas que envuelven a cada visitante en una atmósfera de paz, que invita siempre a regresar.\nNo esperes a las vacaciones, ¡elegí un fin de semana en Cariló!', 15000, '2022-01-04', '2022-01-11', 'CATEGORY1'),
    (8, 'Calafate y Glaciar Perito Moreno, una escapada inolvidable', 'El Calafate', 'El Calafate te espera para disfrutar de unos días de desconexión en la naturaleza. Con las montañas como escenario de fondo, te encontrarás con paisajes que se transforman en un gran lugar para la contemplación.\n En tu escapada, tendrás un hotel con desayuno y estará incluida una excursión hacia el Glaciar Perito Moreno. Al llegar al Glaciar, podrás apreciar esta obra de la naturaleza, disfrutando de diferentes balcones que ofrecen hermosas vistas panorámicas.\n¡Escapate a El Calafate y dejá que el aire del sur renueve tu energía!', 20000, '2022-01-18', '2022-01-25', 'CATEGORY2'),
    (9, 'Desconexión y Naturaleza en Pilar', 'Pilar', 'Encontrá en Pilar el lugar ideal para renovar energías a minutos de tu casa. Sin dudas, es un gran plan para escaparse de la rutina.\n Durante el día, vas a poder sumergite en una atmósfera de relax y disfrutar de momentos mágicos en el hidromasaje, el sauna, las piscinas y el solárium. Por la noche, los sabores de los mejores restaurantes te esperan para completar una escapada perfecta. ¡No lo pienses más y empezá a imaginar esos días de descanso que necesitás!', 15000,'2022-01-06', '2022-01-09', 'CATEGORY1'),
    (10, '¡Rosario siempre estuvo cerca! Escapate a descubrirla', 'Rosario', 'Rosario esconde cientos de opciones para tu próxima escapada. Naturaleza, gastronomía, historia, deportes, arte o diversión: vos elegís como querés disfrutar de la ciudad.\nDejate tentar por el ritmo de una ciudad que combina a la perfección su centro urbano con un entorno natural donde el río Paraná es protagonista. Sumergirte en unos días diferentes, ideales para cortar con la rutina.\nEmpezá a planear tu fin de semana en Rosario. Con amigos o en pareja, siempre es una buena opción.', 20000, '2022-01-06', '2022-01-09', 'CATEGORY1'),
    (11, 'Gualeguaychú con navegación por el río: para desconectar', 'Gualeguaychú', 'Empezá a imaginar tus días lejos de la rutina. Gualeguaychú promete ser el lugar ideal para vivir los mejores momentos de desconexión.\n En tu escapada, encontrarás una estadía con desayunp. Además, la actividad “Navegación en lancha”, te devolverá la posibilidad de conectarte con la naturaleza.\n Aprovechá esta escapada para desenchufarte de verdad.', 30000, '2022-02-03', '2022-02-015', 'CATEGORY2');

INSERT INTO users (id, name) VALUES
    (1, 'guest');